Implementation of login and account creation
IO2-Team/Backend pull request #4
Opened 2023-03-19 19:35 UTC by kutakw

2023-03-19 20:04 UTC, Xevi8X requested changes
Tyle wyłapałem, ale @REKYAR ma tu głos ostateczny

2023-03-19 20:04 UTC, Xevi8X commented on Controllers/EventOrganizerApi.cs
> +        public virtual async Task<IActionResult> Confirm([FromRoute (Name = "id")][Required]string id, [FromQuery (Name = "code")][Required()]string code)
@REKYAR nie wiem co to robi w c#, musisz zadecydować

2023-03-19 20:04 UTC, Xevi8X commented on Dto/Category.cs
Ogólnie zmiana nazw w plikach z folderu DTO to słaby pomysł w razie ponownego generowania API. Ale po prostu chyba zmianny bedą dodawane przyrostowo.

2023-03-19 20:04 UTC, Xevi8X commented on Extensions/SessionExtension.cs
To nie jest aż tak ważne czy token zawiera jakis kontent pod warunkiem ze bedzie unikatowy. Ale jak jest to zostaw.

2023-03-19 20:04 UTC, Xevi8X commented on Extensions/Extensions.cs
> +                // FIXME: (kutakw) currently in db we got int as events name
Baza już jest ok, just fix it

2023-03-19 20:04 UTC, Xevi8X commented on Extensions/Extensions.cs
> +                // FIXME: (kutakw) where do we keep currently available places?
Nie trzymamy. Musisz zrobić COUNT na tablicy rezerwacji o wlasciwym id

2023-03-19 20:04 UTC, Xevi8X commented on Extensions/Extensions.cs
> +        // FIXME: (kutakw) maybe make these extensions async
Po co?

2023-03-19 20:04 UTC, Xevi8X commented on Controllers/EventOrganizerApi.cs
> +                Time = DateTime.Now.AddDays(1.0),
Wydaj mi sie ze lpeiej w bazie trzymać czas utworzenia. A ważnośc sprawdzać przez porównanie z datą aktualną

2023-03-19 20:04 UTC, Xevi8X commented on Controllers/EventOrganizerApi.cs
> +                Code = (organizer.Email.GetHashCode().ToString()
kod jest wpisywany z palca w aplikacji: max 6 znaków.

2023-03-19 20:11 UTC, kutakw commented on Controllers/EventOrganizerApi.cs
> +        public virtual async Task<IActionResult> Confirm([FromRoute (Name = "id")][Required]string id, [FromQuery (Name = "code")][Required()]string code)
Approve, przeoczenie z mojej strony

2023-03-24 11:13 UTC, kutakw commented on Extensions/Extensions.cs
> +                // FIXME: (kutakw) currently in db we got int as events name
Właśnie niestety tutaj jest wciąż problem w tabeli Events, zarówno kolumna 'name' jak i capacity to inty, a z tego co kojarze to name i place schema mialy byc stringami/varcharami

2023-03-25 18:48 UTC, Xevi8X approved these changes

2023-03-25 18:48 UTC, merged