added session validation and addin categories and listing categories
IO2-Team/Backend pull request #7
Opened 2023-03-21 17:18 UTC by REKYAR

2023-03-23 18:46 UTC, Xevi8X requested changes

2023-03-23 18:46 UTC, Xevi8X commented on Controllers/CategoriesApi.cs
> +                if (Helpers.isSessionValid(_dionizosDataContext, sessionToken, TimeSpan.FromHours(sessionLengthHours)))
`int sessionLengthHours = int.Parse(_config["SessionLengthHours"]);`
To powinno znaleźć się w helperze. Przeciuez nie bedziesztego parsował w kazdym endpoincie

2023-03-23 18:46 UTC, Xevi8X commented on Controllers/CategoriesApi.cs
> +                if (Helpers.isSessionValid(_dionizosDataContext, sessionToken, TimeSpan.FromHours(sessionLengthHours)))
niech Helper znaj juz Data context zeby jedym jego parametrem był sessionToken

2023-03-23 18:46 UTC, Xevi8X commented on Controllers/CategoriesApi.cs
> +                if (Helpers.isSessionValid(_dionizosDataContext, sessionToken, TimeSpan.FromHours(sessionLengthHours)))
Sprawdzanie sesji powinno wgl być najpierwszejsze z pierwszych w kontrolerze

2023-03-23 18:46 UTC, Xevi8X commented on Controllers/CategoriesApi.cs
> +                        return StatusCode(200);
Api przewiduje ze zwrócone zostanie 201 i objekt klasy.

2023-03-23 18:46 UTC, Xevi8X commented on Controllers/CategoriesApi.cs
> +                        return StatusCode(400);
Albo 400 i brak objektu - tu akurat ok.

2023-03-23 18:46 UTC, Xevi8X commented on Controllers/CategoriesApi.cs
>              return new ObjectResult(example);
Rozumiem ze to tymczasowe, zostaw TODO

2023-03-23 18:46 UTC, Xevi8X commented on Controllers/CategoriesApi.cs
>              ? Newtonsoft.Json.JsonConvert.DeserializeObject<List<Category>>(exampleJson)
Po co zostawiony jest example. Usun w całości. example. Dodaj zwykłym sql przykladowe kategorie do bazy i sprawdz czy działa.

2023-03-23 18:46 UTC, Xevi8X commented on Helpers.cs
> +        public static bool isSessionValid(DionizosDataContext dionizosDataContext, string sessionToken, TimeSpan sessionLength)
j.w. - Helper powinien znać kontekt i długosc sesji z properties. Moze nie byc statyczny i bedziemy go wtedy tworzyć lokalnie w kazdej klasie kontrolera.

Idealne rozwiązanie to wzorzec singleton i IoC

2023-03-23 18:46 UTC, Xevi8X commented on Program.cs
> +            builder.Services.AddSingleton<IConfigurationRoot>(config);
otototo, helper tez można wstrzykiwać

2023-03-25 11:11 UTC, Xevi8X requested changes
Nie musisz narazie wprowadzać zmioan. Omowimy uwagi na spotkaniu bo bedzie to dotyczyć też @kutakw

2023-03-25 11:11 UTC, Xevi8X commented on Controllers/CategoriesApi.cs
> +            int sessionLengthHours = _helper.GetSessionLengthHours();
Wciągnąc do helpera

2023-03-25 11:11 UTC, Xevi8X commented on Controllers/CategoriesApi.cs
> +            if (_helper.Validate(sessionToken, TimeSpan.FromHours(sessionLengthHours)))
zamiast wielokrotnie zagnieżdzonych if'ów skorzystać z konstrukcji if return

2023-03-25 11:11 UTC, Xevi8X commented on Helpers.cs
> +        public int GetSessionLengthHours()
zmienimy na sekundy - sesja zwykle traw ok 20min ale niektóre aplikacje życzą sobie 30sek.

2023-03-25 13:30 UTC, kutakw commented on Helpers.cs
> +            return _dionizosDataContext.Sessions.Count(x => x.Token == sessionToken && x.Time.ToUniversalTime() >= (DateTime.UtcNow - sessionLength)) > 0;
```suggestion
            return _dionizosDataContext.Sessions.Any(x => x.Token == sessionToken && x.Time.ToUniversalTime() >= (DateTime.UtcNow - sessionLength));
```

2023-03-25 17:57 UTC, REKYAR commented on Controllers/CategoriesApi.cs
> +                if (Helpers.isSessionValid(_dionizosDataContext, sessionToken, TimeSpan.FromHours(sessionLengthHours)))
zrobione

2023-03-25 18:13 UTC, Xevi8X approved these changes

2023-03-25 18:13 UTC, merged